djangito/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('sns/', include('ses_sns.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

urlpatterns = [
    path("", views.ContactUploadListView.as_view(), name="contact_upload_list"),
    path("create", views.ContactUploadCreateView.as_view(), name="contact_upload_create"),
    path("detail/<pk>", views.ContactUploadDetailView.as_view(), name="contact_upload_detail"),
    path("csv", views.GenerateFakeContactList.as_view(), name="contact_generate"),
]

myapp/models.py
from django.db import models

from myapp.tuples import CONTACT_UPLOAD_STATUSES


class ContactUpload(models.Model):
    STATUS_CHOICES = (
        (CONTACT_UPLOAD_STATUSES.pending, 'Pending'),
        (CONTACT_UPLOAD_STATUSES.processing, 'Processing'),
        (CONTACT_UPLOAD_STATUSES.finished, 'Finished'),
        (CONTACT_UPLOAD_STATUSES.failed, 'Failed'),
    )
    contact_file = models.FileField(upload_to='uploads/%Y/%m/%d/')
    created_dt = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=CONTACT_UPLOAD_STATUSES.pending
    )

    class Meta:
        verbose_name = 'Contact Upload'
        verbose_name_plural = 'Contact Uploads'
        ordering = ('-pk',)


class Contact(models.Model):
    email = models.EmailField()
    has_mx_records = models.BooleanField(default=None, null=True)
    upload = models.ForeignKey(ContactUpload, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'
        ordering = ('email',)

myapp/views.py
from io import BytesIO

from celery import current_app
from django.core.cache import cache
from django.db import transaction
from django.http import FileResponse
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, TemplateView
from faker import Faker

from myapp.models import ContactUpload
from myapp.tuples import CONTACT_UPLOAD_STATUSES


class ContactUploadListView(TemplateView):
    model = ContactUpload
    template_name = 'myapp/list.html'

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs['object_list'] = cache.get('contact_lists', [])
        return kwargs


class ContactUploadCreateView(CreateView):
    template_name = 'myapp/create.html'
    model = ContactUpload
    fields = ('contact_file',)

    def get_success_url(self):
        return reverse('contact_upload_detail', args=(str(self.object.pk),))

    def form_valid(self, form):
        response = super().form_valid(form)
        transaction.on_commit(
            lambda: current_app.send_task(
                "process_uploaded_file",
                kwargs={"upload_id": self.object.id}, queue="long"))
        return response


class ContactUploadDetailView(DetailView):
    template_name = 'myapp/detail.html'
    model = ContactUpload
    object: ContactUpload

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        if self.object.status == CONTACT_UPLOAD_STATUSES.finished:
            kwargs['processing_finished'] = True
        return kwargs


class GenerateFakeContactList(View):
    def generate_data(self, number_contacts):
        fake = Faker('en_US')

        memory_file = BytesIO()
        content = '\n'.join([fake.email() for i in range(number_contacts)]).encode('utf-8')
        memory_file.write(content)
        memory_file.seek(0)
        return memory_file

    def get(self, request, *args, **kwargs):
        number_contacts = 100
        if request.GET.get('number_contacts'):
            number_contacts = int(request.GET.get('number_contacts'))
        return FileResponse(self.generate_data(number_contacts), filename="output.csv", as_attachment=True)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
</head>

<body>
{% block content %}{% endblock %}
</body>
</html>

myapp/templates/myapp/create.html
{% extends "myapp/base.html" %}
{% block title %}Upload new file{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Viewing Contacts Upload #{{ object.pk }}{% endblock %}

{% block content %}
    <h1>{{ object.contact_file.name }}</h1>
    <h2>Status: {{ object.get_status_display }}</h2>
    {% if processing_finished %}
        <h3>Total contacts found: {{ object.contact_set.all.count }}</h3>
    {% else %}
        <script>
            setTimeout(function () {
                window.location.reload();
            }, 3000);
        </script>
    {% endif %}

    <table>
        <tr>
            <th>Email</th>
            <th>MX Found</th>
        </tr>
        {% for contact in object.contact_set.all %}
            <tr>
                <td>{{ contact.email }}</td>
                <td>{{ contact.has_mx_records|yesno:"✅,❌,⁇" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

myapp/templates/myapp/list.html
{% extends 'myapp/base.html' %}
{% block title %}List of Uploads{% endblock %}
{% block content %}
    <a href="{% url "contact_upload_create" %}">Upload New File</a>
    <br>
    <a href="{% url "contact_generate" %}">Download Fake CSV</a>
    <br>
    <table>
        <tr>
            <th>ID</th>
            <th>FILE</th>
            <th>STATUS</th>
        </tr>
        {% for object in object_list %}
            <tr>
                <td><a href="{{ object.url }}">{{ object.pk }}</a></td>
                <td>{{ object.file }}</td>
                <td>{{ object.status }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}